apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: postgres-pod
    app: demo-voting-app
  name: postgres-pod
spec:
  containers:
  - image: postgres:15-alpine
    name: postgres
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
