apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: redis-pod
    app: demo-voting-app
  name: redis-pod
spec:
  containers:
  - image: redis
    name: redis
    ports:
      - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
