apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: result-app-pod
    app: demo-voting-app
  name: result-app-pod
spec:
  containers:
  - image: dockersamples/examplevotingapp_result
    name: result-app
    ports:
      - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

