apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: worker-app-pod
    app: demo-voting-app
  name: worker-app-pod
spec:
  containers:
  - image: dockersamples/examplevotingapp_worker
    name: worker-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
