version: "3.9"
services:
  redis:
    image: redis:alpine 
    deploy: 
      replicas: 1
  db:
    image: postgres:15-alpine
    deploy: 
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  vote:
    image: dockersamples/examplevotingapp_vote
    deploy: 
      replicas: 1
    ports:
    - 5000:80
  result:
    image: dockersamples/examplevotingapp_result
    ports:
    - 5001:80
  worker:
    image: dockersamples/examplevotingapp_worker
    deploy: 
      replicas: 1